Update tictactoe.ts
ZeroCho/ts-lecture pull request #4
Opened 2020-11-02 06:46 UTC by SuhyeonP

count 초기화

2020-11-02 06:52 UTC, ZeroCho requested changes
count=0;를
count = 0;로 바꿔주세요.

2020-11-02 07:32 UTC, SuhyeonP commented
이렇게 하면 된건가요,,? ㅠㅠ pull아예 첨하니까 잘 몰라서 죄송해요 ㅠㅠ

2020-11-02 08:29 UTC, ZeroCho commented
아뇨 주석은 지워주시고 띄어쓰기를 넣어주세요. 다른 코드와 코딩 스타일을 맞춰주세요.

2020-11-03 09:07 UTC, merged

2020-11-03 09:08 UTC, ZeroCho commented
👍